name: RISE
favicon: null
layout_spectrum: 0.6364190876483917
typography_spectrum: 0.5521857631392777
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.07168849185109138
  lightness: 0.6467378425877541
  saturation: 0.5348582272417843
  rhythmicContrast: 0.54279619990848
purpose: []
