name: RISE
favicon: null
layout_spectrum: 0.18302
typography_spectrum: 0.49369
title: RISE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030208'
    - '#460e1b'
    - '#a6372c'
    - '#fe5d25'
    - '#c75b34'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.54279619990848
purpose: []
